### ISSUE TITLE
Working environment for the repo

### ISSUE THREAD

**Issue by naveenrpendli** [conversationai/unintended-ml-bias-analysis#106]
Hello Authors ,

This is an impressive work and I'm trying hard from last couple weeks to setup an env to reproduce it, but I'm having hard time with the packages and its depedencies. Can you please provide me a working environment.

**Comment by idk3** [comment]
Hi naveenrpendli,

Thank you for your interest! Just to confirm, have you tried the setup script in https://github.com/conversationai/unintended-ml-bias-analysis/blob/master/setup.py?

Thanks, and all the best,
Ian

**Comment by naveenrpendli** [comment]
Yes, I have tried that and as some of the dependencies are not working I cannot proceed forward. Tensorflow is one of them that is a roadblock to me.

**Comment by naveenrpendli** [comment]
It would be a great help if you can share the working env to me and I can go-ahead with the experiment. I needed it badly to do understand this work to proceed further.

**Comment by sorensenjs** [comment]
We've updated a few things, it now works with python 3 and has some unit tests. Can you try again and if you're still having problems provide the commands to repro what you're seeing, or at least provide the error messages.
