### ISSUE TITLE
Accessing data since archival

### ISSUE THREAD

**Issue by bricha2** [conversationai/unintended-ml-bias-analysis#137]
Hello,

I am trying to access the wiki test, train, and validate files that were originally at https://raw.githubusercontent.com/conversationai/unintended-ml-bias-analysis/master/data/. Is there a way to reproduce these files?

Thanks,

**Comment by sorensenjs** [comment]
You can access the previous checkpoint, example:
https://raw.githubusercontent.com/conversationai/unintended-ml-bias-analysis/e02b9f12b63a39235e57ba6d3d62d8139ca5572c/data/wiki_test.csv

**Comment by bricha2** [comment]
Thanks!
