### ISSUE TITLE
'ToxModel' object has no attribute 'prep_data_and_score'

### ISSUE THREAD

**Issue by wdma** [conversationai/unintended-ml-bias-analysis#40]
I am trying to do an initial run of Train_Toxicity_Model and am encountering the above error message at the final step:

debias_model.prep_data_and_score(debias_test['comment'], debias_test['is_toxic'])

Looking at model_tool.py, I cannot figure out what this step does, so I cannot guess how to edit the code to make it work.  Please help!

**Comment by nthain** [comment]
Thanks for letting us know about this! That cell in our notebook is a little out of date. I'm preparing a pull request to fix it but in the meanwhile, you should be able to replace prep_data_and_score with score_auc.

So change the line to:

debias_model.score_auc(debias_test['comment'], debias_test['is_toxic'])

**Comment by wdma** [comment]
After thinking about it - that is want I did.  The result is the same as
the previous time it is called (with the wiki data).  I still have to think
about the implications of that result, but it is nice to know that I am on
the right track.  Thank you so much for sharing this code!
